# auto-generated by dev/setup-updater.py
# using metadata from dev/metadata.py

import sys

from setuptools import find_packages, setup

if sys.version_info[0] == 2:
    sys.exit("Sorry, Python 2 is no longer supported.")

setup_info = {
    "name": "walt-vpn",
    "version": "8.2",
    "install_requires": ["walt-common==8.2", "python-daemon<3", "cffi>=1.0.0"],
    "author": "WalT developers",
    "author_email": "walt-contact@univ-grenoble-alpes.fr",
    "keywords": "WalT testbed",
    "license": "3-Clause BSD",
    "url": "https://walt-project.liglab.fr",
    "cffi_modules": ["walt/vpn/ext/build.py:ffibuilder"],
    "description": "WalT VPN components.",
    "entry_points": {
        "console_scripts": [
            "walt-vpn-server = walt.vpn.server:run",
            "walt-vpn-endpoint = walt.vpn.endpoint:run",
            "walt-vpn-client = walt.vpn.client:vpn_client",
            "walt-vpn-setup-credentials = walt.vpn.client:setup_credentials",
            "walt-vpn-ssh-helper = walt.vpn.ssh:helper",
            "walt-vpn-auth-tool = walt.vpn.authtool:run",
            "walt-vpn-setup = walt.vpn.setup:run",
        ]
    },
    "include_package_data": True,
    "setup_requires": ["cffi>=1.0.0"],
}
setup_info.update(packages=find_packages())
setup(**setup_info)
