#!/bin/sh
. walt-script-common

export vnode_mode="$1"  # used in walt-net-service-handler
while true
do
    busybox nc -l -p 12346 -e walt-net-service-handler
    echo "[walt:bg] walt-net-service: restarting nc"
done

