#!/bin/sh
. walt-script-common

echo "[walt:bg] walt-fs-watchdog started."

while [ 1 ]
do
    walt-timeout 20 ls -l /mnt/nfsroot/bin/walt-init >/dev/null || {
        echo "[walt:bg] Network filesystem share was lost! Will reboot."
        trigger_walt_reboot reboot
        exit 1
    }
    busybox sleep 5
done
