#!/bin/sh
. /bin/walt-script-common --catch-errors

echo "[bg] walt-fs-watchdog started."

while [ 1 ]
do
    /bin/walt-timeout 20 ls -l mnt/nfsroot/bin/walt-init >/dev/null || {
        echo "[bg] Network filesystem share was lost! Will reboot."
        trigger_walt_reboot reboot
        exit 1
    }
    sleep 5
done
