#!/bin/busybox sh
set -e

# Check we are PID 1.
if [ "$$" -ne 1 ]
then
    echo "This is the init script of walt nodes." >&2
    echo "It is only useful when the node is booting. Exiting." >&2
    exit 1
fi

MOUNT='busybox mount'
UMOUNT='busybox umount'
ROOTFS='/tmp/rootfs'
# To activate walt-init logging, create a directory
# /persist/logs/walt-init on the node.
# If present, log files will be written at each bootup.
OPTIONAL_LOGS_DIR="$ROOTFS/mnt/fs_final/persist/logs/walt-init"
ROOTFS_BUSYBOX_APPLETS="
    sh ls ln timeout reboot sleep nc chroot
    mktemp mkfifo sed cat rm cp basename date
"
IMAGE_SCRIPTS="
    /bin/walt-env
    /bin/walt-log-tee
    /bin/walt-log-cat
    /bin/walt-log-echo
    /bin/_walt_internal_/walt-run-script
    /bin/_walt_internal_/walt-fs-watchdog
    /bin/_walt_internal_/walt-net-service
    /bin/_walt_internal_/walt-notify-bootup
    /bin/_walt_internal_/walt-rpc
    /bin/_walt_internal_/walt-clock-sync
    /bin/_walt_internal_/walt-timeout
    /bin/_walt_internal_/walt-hybrid-boot
    /bin/_walt_internal_/walt-script-common
"

admin_sh()
{
    echo 'Starting a shell.'
    echo '(the node will be rebooted on exit.)'
    console="$1"
    if [ "$console" != "unknown" ]
    then
        # see http://www.busybox.net/FAQ.html#job_control
        setsid sh -c "exec sh -i <>/dev/${console} 2>&1"
    else
        echo "Sorry, no job control."
        sh -i
    fi
    reboot -f
}

detect_input() {
    echo '>>> Issue detected!               <<<'
    echo 'Will reboot... (or press <ENTER> now for a shell)'
    wait_for_input_line_shortly 5 >/dev/null 2>&1
}

reboot_or_sh()
{
    if [ ! -d "/sys/class" ]
    then
        $MOUNT -t sysfs none /sys || true
    fi
    run_shell="no"
    if [ -e "/sys/class/tty/console/active" ]
    then
        # if we could properly detect the console devices, detect
        # on which one the standard input is connected
        # by trying to read <ENTER> on each of them successively
        for console_device in $(cat /sys/class/tty/console/active)
        do
            if detect_input <>/dev/$console_device 1>&0
            then
                curr_console_device=$console_device
                run_shell="yes"
                break
            fi
        done
    else
        # if we could not detect the console devices
        # just wait for <ENTER> on standard input
        if detect_input
        then
            curr_console_device="unknown"
            run_shell="yes"
            break
        fi
    fi
    if [ "$run_shell" = "yes" ]
    then
        admin_sh $curr_console_device
    else
        busybox reboot -f
    fi
}

trap reboot_or_sh EXIT

do_mounts()
{
    [ -e "/proc/self" ] || $MOUNT -t proc none /proc
    [ -e "/dev/null" ] || $MOUNT -t devtmpfs none /dev
    $MOUNT -t tmpfs none /tmp
}

capturing_logs()
{
    [ -d "$OPTIONAL_LOGS_DIR" ]
}

init_logging()
{
    log_file_base="$OPTIONAL_LOGS_DIR/walt-init"
    # prepare stdout and sterr log files
    for ext in "out" "err"
    do
        # we concatenate to possibly existing content
        # from previous bootups.
        # first, add a header with a date
        echo >> $log_file_base.$ext
        echo "-----" >> $log_file_base.$ext
        date >> $log_file_base.$ext
    done
    # avoid NFS buffers by remounting with 'sync' option
    $MOUNT -o remount,sync $ROOTFS/mnt/fs_final/persist
    # redirect
    exec 1>>$log_file_base.out 2>>$log_file_base.err
    set -x
}

copy_busybox_to_rootfs()
{
    # copy binary
    cp "$(which busybox)" $ROOTFS/bin/
    # check if ldd is available
    if ! which ldd >/dev/null
    then
        echo "Warning: no ldd -- If busybox is a dynamic executable, this script will not work."
        return
    fi
    # check needed shared libraries
    if ! bin_deps="$(ldd $(which busybox))"
    then
        # busybox is probably static, nothing more to do
        return
    fi
    # copy shared libraries
    echo "$bin_deps" | busybox awk '{print $(NF-1)}' | while read lib
    do
        if [ -f "$lib" ]
        then
            destdir="$ROOTFS/$(dirname $lib)"
            mkdir -p "$destdir"
            cp "$lib" "$destdir"
        fi
    done
}

run_script_in_rootfs()
{
    cd $ROOTFS
    mode="$1"; shift
    if [ "$mode" = "fg" ]
    then
        busybox chroot . bin/walt-run-script "$@"
    else
        busybox chroot . bin/walt-run-script "$@" &
    fi
}

prepare_rootfs()
{
    mkdir $ROOTFS
    cd $ROOTFS
    mkdir -p tmp bin dev proc sys mnt/nfsroot
    copy_busybox_to_rootfs
    for image_script in $IMAGE_SCRIPTS
    do
        cp $image_script bin/
    done
    for c in $ROOTFS_BUSYBOX_APPLETS
    do
        ln -s busybox bin/$c
    done
    # make the NFS mount, /proc, /dev, /sys visible in the rootfs
    $MOUNT -o bind,ro /     mnt/nfsroot
    $MOUNT -o bind    /proc  proc
    $MOUNT -o bind    /dev  dev
    if [ -d "/sys/class" ]
    then
        $MOUNT -o bind    /sys  sys
    else
        $MOUNT -t sysfs none sys
    fi
    cd - >/dev/null
}

# we will start background processes in a chroot rooted in memory
# (at /tmp/rootfs, and /tmp is a tmpfs filesystem):
# * a network fs watchdog that will monitor the network filesystem
#   mount and reboot the node if fs connection is lost
# * a lightweight network service able to fulfill soft-reboot and
#   led blink requests coming from the server
# * a service which establishes a permanent TCP connection to the
#   server, in order to reflect node bootup status
# We could not start those processes on the final rootfs because
# they could be affected by NFS disconnections or various other OS
# issues possibly occurring on the image.
# And we need those features to be as robust as possible, in order
# to avoid the case of unresponsive nodes with no way to reboot them
# remotely.
# It may seem dirty to keep background processes running when we
# exec the real OS init, but this is a simple and generic way to
# handle these features in all WalT images.
start_background_processes()
{
    run_script_in_rootfs bg 0 walt-fs-watchdog
    run_script_in_rootfs bg 0 walt-net-service
    run_script_in_rootfs bg 0 walt-notify-bootup
}

# since we share the NFS export across all rpi nodes,
# this mount must remain read-only.
# in order to enable writes, each rpi will write
# the filesystem changes in memory.
# this is done by using a 'union' filesystem
# called overlayfs.
mount_final_union()
{
    cd $ROOTFS/mnt
    mkdir -p fs_rw fs_work fs_final
    # creating the union
    # lowerdir=/: the nfs mount (that should remain read-only)
    # upperdir=fs_rw: the place to hold the filesystem changes
    # workdir=fs_work: a workdir for the overlay filesystem
    # uniondir=fs_final: the mount point of the union
    mount_union / fs_rw fs_work fs_final
}

# This is the persistent mount point, available even across reboots.
# Data are stored on the server through an NFS share.
mount_persistent()
{
    cd $ROOTFS/mnt

    # Compute persistent storage path:
    # <server-ip>:/var/lib/walt/nodes/<hostname>/persist
    # Caution: with NFSv4, client first mounts /var/lib/walt/nodes,
    # then retrieves /var/lib/walt/nodes/<mac>/fs symlink target,
    # and mounts this target path. Thus the mount target, as
    # reported by findmnt for instance, is this second step
    # mount target, of the form /var/lib/walt/images/<image-id>/fs.
    server_ip="$(grep ' / ' /proc/mounts | sed -e 's/:.*//')"
    hostname="$(busybox uname -n)"
    persist_path="${server_ip}:/var/lib/walt/nodes/${hostname}/persist"

    # Mount the share
    mkdir -p fs_final/persist
    $MOUNT -t nfs -o rw,relatime,vers=3,nolock \
           "${persist_path}" fs_final/persist 2>/dev/null || {
        echo "/persist was not mounted (cf. walt node config)"
        rm -rf fs_final/persist
    }
}

has_mount()
{
    mp="$1"
    $MOUNT | grep -q "[[:space:]]${mp}[[:space:]]"
}

update_mounts()
{
    $MOUNT -o bind /dev $ROOTFS/mnt/fs_final/dev
    has_mount /run && $MOUNT -o bind /run $ROOTFS/mnt/fs_final/run
    mkdir $ROOTFS/mnt/fs_final/run/origfs
    $MOUNT -o bind / $ROOTFS/mnt/fs_final/run/origfs
    $UMOUNT /proc
}

run_real_init()
{
    cd $ROOTFS/mnt/fs_final
    exec busybox chroot . sbin/init $@
}

record_env_var()
{
    echo "export $1=$2" >> $ROOTFS/bin/walt-env
}

detect_disks()
{
    for mod in ata_piix sd_mod
    do
        modprobe $mod >/dev/null 2>&1 || true
    done
}

# let's go
export PATH="$PATH:/bin/_walt_internal_"
. walt-script-common
walt-log-echo "walt-init" "Starting up."
boot_step_label_cr          "Mounting..."
do_mounts
boot_step_label_cr          "Preparing rootfs..."
prepare_rootfs
boot_step_label             "Detecting boot-mode..."
detect_disks
if run_script_in_rootfs fg 1 walt-hybrid-boot detect
then
    mode_variant="$(run_script_in_rootfs fg 1 walt-hybrid-boot mode-variant)"
    boot_step_label_replace "Detecting boot-mode: hybrid (${mode_variant})"
    if run_script_in_rootfs fg 1 walt-hybrid-boot mount
    then
        boot_mode="hybrid-${mode_variant}"
    else
        boot_step_label_cr  "Falling back to boot-mode: network"
        boot_mode="network"
    fi
else
    boot_step_label_replace "Detecting boot-mode: network"
    boot_mode="network"
fi
if [ "$boot_mode" = "network" ]
then
    boot_step_label_cr      "Mounting filesystem union..."
    mount_final_union
fi
record_env_var "walt_boot_mode" "${boot_mode}"
boot_step_label_cr          "Mounting persistent filesystem"
mount_persistent
capturing_logs && \
    boot_step_label_cr      "Starting to capture logs..."
capturing_logs && init_logging
boot_step_label_cr          "Preparing target fs sub-mounts..."
update_mounts
boot_step_label_cr          "Setting clock..."
run_script_in_rootfs fg 0 walt-clock-sync
boot_step_label_cr          "Starting bg processes..."
start_background_processes
boot_step_label_cr          "Starting walt image init..."
walt-log-echo "walt-init" "Handing over to WALT image init."
run_real_init
