version: 2

build:
  os: "ubuntu-22.04"
  tools:
    python: "3.10"

sphinx:
  fail_on_warning: true
  configuration: client/walt/client/doc/sphinx/conf.py

python:
  install:
    - requirements: client/walt/client/doc/sphinx/requirements.txt


