import numpy as np
import socket
import sys
from pathlib import Path

from walt.common.unix import bind_to_random_sockname
from walt.server.tools import (
        get_walt_subnet,
        np_apply_str_pattern,
        np_str_pattern,
        update_conf_file,
)

WALT_SUBNET = get_walt_subnet()
NBFSD_EXPORTS_PATH = Path("/etc/nbfsd/exports.d/walt.exports")
NBFSD_CTL_SOCK_PATH = Path("/run/nbfsd/ctl.sock")

FILE_TEMPLATE = f"""\
# WALT NBFS exports: this file is automatically generated.

# OS image exports
[image-exports]

# Read-Write OS exports for nodes with 'boot.mode=network-persistent'
[node-rw-exports]
"""

IMAGE_EXPORT_PATTERN = np_str_pattern(f"""\
%(path)s {WALT_SUBNET}(fsid=%(fsid)s)\
""")

NODE_RW_EXPORT_PATTERN = np_str_pattern(f"""\
%(path)s {WALT_SUBNET}(fsid=%(fsid)s)\
""")


def wf_update_nbfs(wf, image_exports, node_rw_exports, **env):
    nbfs_conf = compute_nbfs_conf(image_exports, node_rw_exports)
    if update_conf_file(NBFSD_EXPORTS_PATH, nbfs_conf):
        notify_nbfsd()
    wf.next()


def wf_cleanup_nbfs(wf, **env):
    NBFSD_EXPORTS_PATH.unlink(missing_ok=True)
    notify_nbfsd()
    wf.next()


def compute_nbfs_conf(image_exports, node_rw_exports):
    if len(image_exports) > 0:
        image_exports_str = "\n".join(
            np_apply_str_pattern(IMAGE_EXPORT_PATTERN, image_exports))
    else:
        image_exports_str = '# (none)'
    if len(node_rw_exports) > 0:
        node_rw_exports_str = "\n".join(
            np_apply_str_pattern(NODE_RW_EXPORT_PATTERN, node_rw_exports))
    else:
        node_rw_exports_str = '# (none)'
    nbfs_conf = FILE_TEMPLATE.replace("[image-exports]", image_exports_str)
    nbfs_conf = nbfs_conf.replace("[node-rw-exports]", node_rw_exports_str)
    return nbfs_conf


def notify_nbfsd():
    # NBFSD_CTL_SOCK should exist if nbfsd is installed and running
    if NBFSD_CTL_SOCK_PATH.exists():
        nbfsd_ctl_sock = socket.socket(socket.AF_UNIX, socket.SOCK_DGRAM)
        bind_to_random_sockname(nbfsd_ctl_sock)
        try:
            nbfsd_ctl_sock.connect(str(NBFSD_CTL_SOCK_PATH))
            nbfsd_ctl_sock.send(b"RELOAD_CONF")
            resp = nbfsd_ctl_sock.recv(1024)
            if resp != b"OK":
                print("Error: RELOAD_CONF request to nbfsd failed.",
                      file=sys.stderr)
        except Exception as e:
            print(f"Error: sending RELOAD_CONF request to nbfsd failed: {e}")
        finally:
            nbfsd_ctl_sock.close()
