import numpy as np
import sys
from pathlib import Path

from walt.common.tools import succeeds
from walt.server.mount.tools import (
        get_image_mount_path,
        get_node_rw_fsid,
        get_node_rw_mount_path,
)
from walt.server.tools import (
        get_walt_subnet,
        np_apply_str_pattern,
        np_substr,
        np_split_words,
        np_str_pattern,
        update_conf_file,
)

WALT_SUBNET = get_walt_subnet()
NFS_COMMON_OPTIONS = "sync,no_root_squash,no_subtree_check"
NFSD_EXPORTS_PATH = Path("/etc/exports.d/walt.exports")

FILE_TEMPLATE = f"""\
# WALT NFS exports: this file is automatically generated.

# Access to node symlinks (necessary for NFSv4).
/var/lib/walt/nodes {WALT_SUBNET}(ro,{NFS_COMMON_OPTIONS})

# OS image exports
[image-exports]

# Read-Write OS exports for nodes with 'boot.mode=network-persistent'
[node-rw-exports]

# Exports for [node]:/persist mounts
[persist-exports]
"""

DT_EXPORT = np.dtype([("path", object),
                      ("fsid", object)])

IMAGE_EXPORT_PATTERN = np_str_pattern(f"""\
%(path)s {WALT_SUBNET}(fsid=%(fsid)s,ro,{NFS_COMMON_OPTIONS})\
""")

NODE_RW_EXPORT_PATTERN = np_str_pattern(f"""\
%(path)s {WALT_SUBNET}(fsid=%(fsid)s,rw,{NFS_COMMON_OPTIONS})\
""")

PERSIST_EXPORT_PATTERN = np_str_pattern(f"""\
%(path)s {WALT_SUBNET}(rw,{NFS_COMMON_OPTIONS})\
""")


def _run_exportfs():
    if not succeeds("exportfs -r -f"):
        print("Warning: exportfs failed!", file=sys.stderr)


def wf_update_nfs(wf, image_exports, node_rw_exports,
                  persist_exports, **env):
    nfs_conf = compute_nfs_conf(
        image_exports, node_rw_exports, persist_exports)
    if update_conf_file(NFSD_EXPORTS_PATH, nfs_conf):
        _run_exportfs()
    wf.next()


def wf_cleanup_nfs(wf, **env):
    NFSD_EXPORTS_PATH.unlink(missing_ok=True)
    _run_exportfs()
    wf.next()


def wf_compute_nfs_info(wf, new_status, db_nodes, **env):
    # sort new status and convert it to a numpy array
    new_status = np.array(sorted(new_status), str)
    # compute image exports
    mask_image_mounts = np.char.startswith(new_status, "MOUNT-IMAGE")
    image_mounts = new_status[mask_image_mounts]
    arr_exports = np.empty(len(image_mounts), DT_EXPORT)
    if len(image_mounts) > 0:
        image_mounts_ids = np_split_words(image_mounts)[:,1]
        arr_exports["path"] = get_image_mount_path(image_mounts_ids)
        arr_exports["fsid"] = np_substr(image_mounts_ids, 0, 32)
    wf.update_env(image_exports=arr_exports)
    # compute node-rw exports
    mask_node_rw_mounts = np.char.startswith(new_status, "MOUNT-NODE-RW")
    node_rw_mounts = new_status[mask_node_rw_mounts]
    arr_exports = np.empty(len(node_rw_mounts), DT_EXPORT)
    if len(node_rw_mounts) > 0:
        node_rw_mounts_args = np_split_words(node_rw_mounts)
        node_macs = node_rw_mounts_args[:,1]
        image_ids = node_rw_mounts_args[:,2]
        image_fullnames = node_rw_mounts_args[:,3]
        node_rw_mountpoints = get_node_rw_mount_path(
                node_macs, image_ids, image_fullnames
        )
        node_rw_fs_ids = get_node_rw_fsid(node_rw_mountpoints)
        arr_exports = np.empty(len(node_rw_mounts), DT_EXPORT)
        arr_exports["path"] = node_rw_mountpoints
        arr_exports["fsid"] = node_rw_fs_ids
    wf.update_env(node_rw_exports=arr_exports)
    # compute persist exports
    arr_exports = np.empty(len(db_nodes), DT_EXPORT)
    if len(db_nodes) > 0:
        arr_exports["path"] = (
            "/var/lib/walt/nodes/" +
            db_nodes.mac + "/persist_dirs/" + db_nodes.owner
        )
    wf.update_env(persist_exports=arr_exports)
    wf.next()


def compute_nfs_conf(image_exports, node_rw_exports, persist_exports):
    if len(image_exports) > 0:
        image_exports_str = "\n".join(
            np_apply_str_pattern(IMAGE_EXPORT_PATTERN, image_exports))
    else:
        image_exports_str = '# (none)'
    if len(node_rw_exports) > 0:
        node_rw_exports_str = "\n".join(
            np_apply_str_pattern(NODE_RW_EXPORT_PATTERN, node_rw_exports))
    else:
        node_rw_exports_str = '# (none)'
    if len(persist_exports) > 0:
        persist_exports_str = "\n".join(
            np_apply_str_pattern(PERSIST_EXPORT_PATTERN, persist_exports))
    else:
        persist_exports_str = '# (none)'
    nfs_conf = FILE_TEMPLATE.replace("[image-exports]", image_exports_str)
    nfs_conf = nfs_conf.replace("[node-rw-exports]", node_rw_exports_str)
    nfs_conf = nfs_conf.replace("[persist-exports]", persist_exports_str)
    return nfs_conf
