#!/usr/bin/env python3
import sys, os
from collections import OrderedDict
sys.path.append(os.getcwd())
from dev.tools.pretty import pprint_dict
from dev.metadata import PACKAGE_GENERIC_INFO, PACKAGE_SPECIFIC_INFO

info_file_template = """\
# auto-generated by dev/info-updater.py
# using metadata from dev/metadata.py

SETUP_INFO = %(setup_info)s
"""

# read __version__ variable
exec(compile(open('common/walt/common/version.py').read(), 'common/walt/common/version.py', 'exec'))

# generate info.py in each pypi package directory
versions_info = dict(
    upload = __version__
)

for package_name, package_specific in PACKAGE_SPECIFIC_INFO.items():
    setup_info = OrderedDict()
    setup_info.update(name = package_name)
    version = package_specific['version_str'] % versions_info
    setup_info.update(version = version)
    install_requires = [ requirement % versions_info \
        for requirement in package_specific['requires'] ]
    setup_info.update(install_requires = install_requires)
    if 'extras_require' in package_specific:
        extras_require = {
            feature: [ (req % versions_info) for req in requirements ] \
            for (feature, requirements) in \
                    package_specific['extras_require'].items()
        }
        setup_info.update(extras_require = extras_require)
    setup_info.update(sorted(PACKAGE_GENERIC_INFO.items()))
    setup_info.update(sorted(package_specific['setup'].items()))
    new_info_file = info_file_template % dict(
        setup_info = pprint_dict(setup_info)
    )
    subdir = package_specific['subdir']
    subdir_as_path = subdir.replace('-', '/')
    with open("%(subdir)s/walt/%(subdir_as_path)s/info.py" % dict(
            subdir = subdir, subdir_as_path = subdir_as_path), 'w') as f:
        f.write(new_info_file)
