#!/bin/sh
#
# walt-vpn-client       Establishes a vpn to walt server
#

DAEMON="walt-vpn-client"
DAEMON_PATH="$(which $DAEMON)"
PIDFILE="/var/run/$DAEMON.pid"
CONF=/etc/default/walt-vpn-node
export HOME=/root

# Make sure the conf is OK
[ -f $CONF ] || {
    echo "Missing file '$CONF'." >&2
    exit 1
}
source $CONF
[ ! -z "$WALT_VPN_ENTRYPOINT" ] || {
    echo "File $CONF should define var WALT_VPN_ENTRYPOINT." >&2
    exit 1
}

umask 077

start() {
	if [ ! -f /root/.ssh/id_ecdsa_walt_vpn ]
	then
		echo "Setting up VPN credentials with walt server..."
		mount -o remount,rw /
		walt-vpn-setup-credentials $WALT_VPN_ENTRYPOINT
		mount -o remount,ro /
	fi
	if [ ! -f /root/.ssh/id_ecdsa_walt_vpn ]
	then
		echo "Could not get VPN credentials. Rebooting."
		reboot
		return
	fi

	echo "Starting vpn client: "
	start-stop-daemon -S -q -p "$PIDFILE" -a "$DAEMON_PATH" \
		-- "$WALT_VPN_ENTRYPOINT"
	status=$?
	if [ "$status" -eq 0 ]; then
		echo "OK"
	else
		echo "FAIL"
	fi
	return "$status"
}
stop() {
	printf 'Stopping vpn client: '
	start-stop-daemon -K -q -p "$PIDFILE"
	status=$?
	if [ "$status" -eq 0 ]; then
		rm -f "$PIDFILE"
		echo "OK"
	else
		echo "FAIL"
	fi
	return "$status"
}
restart() {
	stop
	start
}

case "$1" in
  start)
	start
	;;
  stop)
	stop
	;;
  restart|reload)
	restart
	;;
  *)
	echo "Usage: $0 {start|stop|restart}"
	exit 1
esac

exit $?

