# auto-generated by dev/setup-updater.py
# using metadata from dev/metadata.py

import sys

from setuptools import find_packages, setup

if sys.version_info[0] == 2:
    sys.exit("Sorry, Python 2 is no longer supported.")

setup_info = {
    "name": "walt-doc",
    "version": "10.0",
    "install_requires": [
        "commonmark>=0.7.5",
        "pygments>=2.2.0",
        "setuptools>=70.0.0",
        "walt-common==10.0",
    ],
    "author": "WalT developers",
    "author_email": "walt-contact@univ-grenoble-alpes.fr",
    "keywords": "WalT testbed",
    "license": "3-Clause BSD",
    "url": "https://walt-project.liglab.fr",
    "description": "WalT doc files and related code.",
    "include_package_data": True,
}
setup_info.update(packages=find_packages())
setup(**setup_info)
