#!/bin/sh

# We consider the node is ready when its
# sshd service is ready to accept connections.
while [ 1 ]
do
    echo | nc 127.0.0.1 22 && break
    sleep 1
done

# connect to server and send notification
nc %(server_ip)s %(walt_server_rpc_port)s >/dev/null << EOF
REQ_API_SESSION
NSAPI
('API_CALL', 'node_bootup_event', (), {})
('CLOSE')
EOF

