#!/bin/sh

# We consider the node is ready when its
# sshd service is ready to accept connections.
while [ 1 ]
do
    echo | nc 127.0.0.1 22 >/dev/null 2>&1 && break
    sleep 1
done

# send notification to server
/bin/walt-rpc node_bootup_event >/dev/null
