# auto-generated by dev/setup-updater.py
# using metadata from dev/metadata.py

import sys

from setuptools import find_packages, setup

if sys.version_info[0] == 2:
    sys.exit("Sorry, Python 2 is no longer supported.")

setup_info = {
    "name": "walt-node",
    "version": "10.0",
    "install_requires": ["walt-common==10.0"],
    "author": "WalT developers",
    "author_email": "walt-contact@univ-grenoble-alpes.fr",
    "keywords": "WalT testbed",
    "license": "3-Clause BSD",
    "url": "https://walt-project.liglab.fr",
    "description": "WalT optional software embedded in images.",
    "entry_points": {
        "console_scripts": [
            "walt-node-setup = walt.node.setup:run",
            "walt-serial-autolog = walt.node.serial.autolog:run",
            "walt-logs-daemon = walt.node.logs.daemon:run",
            "walt-ipxe-kexec-reboot = walt.node.ipxekexec:run",
        ]
    },
    "include_package_data": True,
    "scripts": ["sh/walt-log-monitor", "sh/walt-monitor"],
}
setup_info.update(packages=find_packages())
setup(**setup_info)
