#!/bin/sh

open_null_if_not_done_yet() {
    if [ -z "$_null_opened" ]
    then
        if [ -e "/dev/null" ]
        then
            exec 9>/dev/null
            export _null_opened=1
        else
            return 1
        fi
    fi
}

nostdout() {
    if open_null_if_not_done_yet
    then
        "$@" >&9
    else
        echo "warning: nostdout ignored, /dev/null is not available" >&2
        "$@"
    fi
}

nostderr() {
    if open_null_if_not_done_yet
    then
        "$@" 2>&9
    else
        echo "warning: nostderr ignored, /dev/null is not available" >&2
        "$@"
    fi
}

happy_grep() {
    grep "$@" || true   # always return status ok
}

wait_for_input_line_shortly() {
    nostderr walt-timeout $1 busybox sh -c 'read l && echo "$l"'
}

busybox_has_applet() {
    nostdout nostderr busybox $1 --help
}

run_busybox_or_not() {
    # run as a busybox or direct command
    if [ "$1" = "--prefer-system" ]
    then
        shift
        cmd="$(notsderr busybox which "$1")" || cmd="busybox $1"
    else
        if busybox_has_applet "$1"
        then
            cmd="busybox $1"
        else
            cmd="$1"
        fi
    fi
    shift
    $cmd "$@"
}

possibly_vpn_node() {
    if [ -d /sys/class/net/ ]
    then
        if [ -d /sys/class/net/walt-vpn ]
        then
            echo 1  # yes, it is a VPN node
        else
            echo 0  # no, not a VPN node
        fi
    else
        # At this step of the boot procedure
        # /sys/class/net/ does not exist so
        # we cannot tell.
        # So we return 1 ("possibly" a VPN node).
        echo 1
    fi
}
