#!/bin/sh
. walt-init-common
. walt-init-logging

start_background_processes()
{
    # start bg processes
    # notes:
    # - We run them in /run/walt/mnt/memfs (filesystem in RAM) in order
    #   to make them resist NFS share disconnections.
    # - Using pivot_root changes the root filesystem of all processes
    #   in the mount namespace, so we could not start them as part
    #   of walt-init-memfs: their root would have changed when
    #   transitioning to finalfs. Instead, we start them only now,
    #   when in finalfs, but use chroot to have their root in
    #   /run/walt/memfs.
    cd "/run/walt/mnt/memfs"
    walt_log_bg_script walt-net-service &
    walt_log_bg_script walt-fs-watchdog &
    walt_log_bg_script walt-clock-sync &
    cd /
}

run_real_init()
{
    # call the OS init
    exec /sbin/init "$@"
}

export walt_init_done=1

# start bg processes
boot_step_label_cr          "Starting bg processes..."
start_background_processes

# start image init
boot_step_label_cr          "Starting walt image init..."
walt-log-echo "walt-init" "Handing over to WALT image init."
run_real_init
