#!/bin/sh

open_null_if_not_done_yet() {
    if [ -z "$_null_opened" ]
    then
        if [ -e "/dev/null" ]
        then
            exec 9>/dev/null
            export _null_opened=1
        else
            return 1
        fi
    fi
}

nostdout() {
    if open_null_if_not_done_yet
    then
        "$@" >&9
    else
        echo "warning: nostdout ignored, /dev/null is not available" >&2
        "$@"
    fi
}

nostderr() {
    if open_null_if_not_done_yet
    then
        "$@" 2>&9
    else
        echo "warning: nostderr ignored, /dev/null is not available" >&2
        "$@"
    fi
}

happy_grep() {
    grep "$@" || true   # always return status ok
}

wait_for_input_line_shortly() {
    nostderr walt-timeout $1 busybox sh -c 'read l && echo "$l"'
}

busybox_has_applet() {
    nostdout nostderr busybox $1 --help
}

run_busybox_or_not() {
    # run as a busybox or direct command
    if [ "$1" = "--prefer-system" ]
    then
        shift
        cmd="$(notsderr busybox which "$1")" || cmd="busybox $1"
    else
        if busybox_has_applet "$1"
        then
            cmd="busybox $1"
        else
            cmd="$1"
        fi
    fi
    shift
    $cmd "$@"
}

possibly_vpn_node() {
    if [ -d /sys/class/net/ ]
    then
        # If the OS provides the /sys/class/net/ file hierarchy,
        # we can verify if the node created a network interface
        # called walt-net.
        if [ -d /sys/class/net/walt-vpn ]
        then
            echo 1  # yes, it is a VPN node
        else
            echo 0  # no, not a VPN node
        fi
    else
        # If not, we just mirror the value of the walt_vpn_node
        # variable specified by the server in /bin/walt-env.
        # There's no way to detect if the node is VPN-capable
        # but did not activate the VPN because it just booted inside
        # the WALT network. In this case, we return 1 too, i.e.,
        # this is *possibly* a VPN node.
        echo "$walt_vpn_node"
    fi
}
