#!/bin/sh

start_background_processes()
{
    # check if walt-init logs are enabled
    log_dir="/persist/logs/walt-init"
    if [ -d "$log_dir" ]
    then
        rootfs_log_dir="/mnt$log_dir"
    else
        log_dir=""
        rootfs_log_dir=""
    fi
    # start bg processes.
    # walt-fs-watchdog is run with chroot in the rootfs,
    # a tmpfs in RAM where the busybox binary has been copied,
    # in order to be able to run properly in case of NFS share
    # disconnection.
    walt-log-script bg "$log_dir" walt-net-service
    walt-log-script bg "$log_dir" walt-notify-bootup
    cd "/run/walt/rootfs"
    busybox chroot . bin/walt-log-script bg "$rootfs_log_dir" walt-fs-watchdog
    cd /
}

run_real_init()
{
    # call the OS init
    exec /sbin/init "$@" </dev/console >/dev/console 2>&1
}

# complete transition to finalfs
. walt-script-common
export walt_init_done=1

# start bg processes
boot_step_label_cr          "Starting bg processes..."
start_background_processes

# start image init
boot_step_label_cr          "Starting walt image init..."
walt-log-echo "walt-init" "Handing over to WALT image init."
run_real_init
