#!/bin/sh

. /bin/walt-env
. /bin/walt-script-base

set -e

# This script aims to dump an archive containing the files created,
# modified or removed by the node compared to the OS image it booted,
# and dumps a corresponding archive on its output.
#
# In order to achieve this, it dumps the upper layer directory of
# the OS root filesystem union. The dump also includes the "/local"
# directory if relevant (hybrid boot modes).
#
# The upper directory is supposed to represent whiteout files as
# device files with major and minor number set to zero.
# This corresponds to Linux's overlay filesystem technique.
#
# In a previous version, we were trying to ignore changes which
# occured during the bootup, but that causes problems. For instance,
# a postgresql instance may proceed with first boot initialization
# during the bootup, and if transmitting only the database changes
# performed after the bootup the resulting image will not work properly.

get_mode_bits() {
    mode="$1"
    charrange="$2"
    echo "$mode" | \
        busybox cut -c "$charrange" | \
        busybox tr -d "-"
}

copy_mode_and_owner() {
    src="$1"
    dst="$2"
    if busybox_has_applet stat
    then
        mode="$(busybox stat -c "%a" "$src")"
        owner="$(busybox stat -c "%U:%G" "$src")"
        busybox chmod "$mode" "$dst"
        busybox chown "$owner" "$dst"
    else
        set -- $(busybox ls -ld "$src")
        mode="$1"
        owner="$3"
        group="$4"
        mode_user="$(get_mode_bits "$mode" "2-4")"
        mode_group="$(get_mode_bits "$mode" "5-7")"
        mode_other="$(get_mode_bits "$mode" "8-10")"
        busybox chmod "u=${mode_user}" "$dst"
        busybox chmod "g=${mode_group}" "$dst"
        busybox chmod "o=${mode_other}" "$dst"
        busybox chown "$owner:$group" "$dst"
    fi
}

clone_dir() {
    if [ ! -e "$2" ]
    then
        busybox mkdir "$2"
        copy_mode_and_owner "$1" "$2"
    fi
}

clone_parent_dirs_of() {
    local src_pdir="$(busybox dirname "$1")"
    local dst_pdir="${tmp_dir}/${src_pdir}"
    if [ ! -d "$dst_pdir" ]
    then
        # depth-first recursion
        clone_parent_dirs_of "$src_pdir"
        clone_dir "$src_pdir" "$dst_pdir"
    fi
}

hard_link_files() {
    busybox mkdir -p "$tmp_dir"
    while read f
    do
        # clone parent directories of $f recursively in $tmp_dir,
        # preserving mode and ownership.
        clone_parent_dirs_of "$f"
        # make a hardlink of $f in $tmp_dir.
        busybox ln "$f" "${tmp_dir}/$f"
    done
}

filter_out_files() {
    busybox grep -v "/log/" | \
    busybox grep -v "\.lock$" | \
    busybox grep -v "machine-id" | \
    busybox grep -v "walt-env" | \
    busybox grep -v "_walt_internal_" | \
    busybox grep -v "README.nonlocal"
}

list_files() {
    busybox find "$1" '(' -type f -o -type l ')' | filter_out_files
}

dump_archive_network_v_boot() {
    tmp_dir="/run/walt/rootfs/tmp/d$$"
    cd /run/walt/rootfs/mnt/fs_rw
    list_files "." | hard_link_files
    cd "${tmp_dir}"
    busybox tar cf - .
    rm -rf "${tmp_dir}"
}

dump_archive_hybrid_v_boot() {
    tmp_dir="/run/walt/rootfs/mnt/hm_part/walt_hybrid/tmp/d$$"
    cd "/run/walt/rootfs/mnt/hm_part/walt_hybrid/${walt_image_id}/diff"
    list_files "." | hard_link_files
    cd "/run/walt/rootfs/mnt/hm_part/walt_hybrid/${walt_image_id}/"
    list_files "./local" | hard_link_files
    cd "${tmp_dir}"
    busybox tar cf - .
    rm -rf "${tmp_dir}"
}

dump_archive_hybrid_p_boot() {
    tmp_dir="/run/walt/rootfs/mnt/hm_part/walt_hybrid/tmp/d$$"
    cd "/run/walt/rootfs/mnt/hm_part/walt_hybrid/${walt_image_id}/diff"
    list_files "." | hard_link_files
    cd "/run/walt/rootfs/mnt/hm_part/walt_hybrid/${walt_image_id}/"
    list_files "./local" | hard_link_files
    cd "${tmp_dir}"
    busybox tar cf - .
    rm -rf "${tmp_dir}"
}

dump_archive() {
    if [ "$walt_boot_mode" = 'network-volatile' ]
    then
        dump_archive_network_v_boot
    elif [ "$walt_boot_mode" = 'network-persistent' ]
    then
        echo "This script should not be called with boot mode " \
             "'$walt_boot_mode'. Aborting." >&2
        exit 1
    elif [ "$walt_boot_mode" = 'hybrid-volatile' ]
    then
        dump_archive_hybrid_v_boot
    elif [ "$walt_boot_mode" = 'hybrid-persistent' ]
    then
        dump_archive_hybrid_p_boot
    fi
}

dump_archive
exit 0
