#!/bin/sh

start_background_processes()
{
    # start bg processes
    # notes:
    # - We run them in /run/walt/rootfs (filesystem in RAM) in order
    #   to make them resist NFS share disconnections.
    # - Using pivot_root changes the root filesystem of all processes
    #   in the mount namespace, so we could not start them as part
    #   of walt-init-rootfs: their root would have changed when
    #   transitioning to finalfs. Instead, we start them only now,
    #   when in finalfs, but use chroot to have their root in
    #   /run/walt/rootfs.
    cd "/run/walt/rootfs"
    # bg scripts may need to access the final filesystem in the rootfs
    walt_mount -o bind / mnt/finalfs
    busybox chroot . bin/walt-log-script bg walt-net-service
    busybox chroot . bin/walt-log-script bg walt-fs-watchdog
    cd /
}

run_real_init()
{
    # call the OS init
    exec /sbin/init "$@"
}

# complete transition to finalfs
. walt-script-common
export walt_init_done=1

# start bg processes
boot_step_label_cr          "Starting bg processes..."
start_background_processes

# start image init
boot_step_label_cr          "Starting walt image init..."
walt-log-echo "walt-init" "Handing over to WALT image init."
run_real_init
