#!/bin/sh

export walt_server_ip=%(server_ip)s
export walt_server_rpc_port=%(walt_server_rpc_port)s
export walt_server_logs_port=%(walt_server_logs_port)s
export walt_server_notify_bootup_port=%(walt_server_notify_bootup_port)s
export walt_image_id=%(walt_image_id)s
export walt_image_size_kib=%(walt_image_size_kib)s
