#!/bin/busybox sh

set -x
exec </dev/console >/dev/console 2>&1

# Check we are PID 1.
if [ "$$" -ne 1 ]
then
    echo "This is the init script of walt nodes." >&2
    echo "It is only useful when the node is booting. Exiting." >&2
    exit 1
fi

ROOTFS='/run/walt/rootfs'
ROOTFS_BUSYBOX_APPLETS="
    basename cat chroot cp date grep ln ls mkdir mkfifo mktemp modprobe
    mount mv nc pivot_root reboot rm sed sh sleep timeout umount uname
"

_run_is_mounted() {
    walt_mount | busybox grep " /run " >/dev/null
}

do_mounts()
{
    # mount /proc and /sys if missing, and if that is the case,
    # record that for cleanup up before running the final init.
    if [ -e "/proc/self" ]
    then
        export had_procfs=1
    else
        walt_mount -t proc proc /proc
        export had_procfs=0
    fi
    if [ -d "/sys/class" ]
    then
        export had_sysfs=1
    else
        walt_mount -t sysfs sysfs /sys
        export had_sysfs=0
    fi
    # mount /dev and /run if missing.
    # in any case, we will not umount them before running the final init
    # because walt bg processes need them.
    if [ ! -e "/dev/null" ]
    then
        walt_mount -t devtmpfs udev /dev
    fi
    if ! _run_is_mounted
    then
        walt_mount -t tmpfs tmpfs /run
    fi
}

autodetect_block_modules() {
    # we need to load at list the modules needed for block devices, and bus
    # modules they are connected to (for hybrid boot modes).
    # the original idea of looking into /sys/devices is borrowed from alpine's
    # /etc/init.d/hwdrivers
    busybox find /sys/devices/ -name modalias -type f -print0 2>/dev/null | \
        busybox xargs -0 busybox sort -u | \
        happy_grep -v \
            "^\(\(acpi\)\|\(platform\)\|\(cpu\)\|\(serio\)\|\(dmi\)\|\(input\)\)"
}

# This function loads modules which we may need and may not be compiled in the kernel.
load_modules() {
    # crc32c may be needed for mounting ext4 filesystems without error (hybrid modes)
    # nbd & zswap: useful for mounting a swap file stored remotely on server
    # if other modules are needed, the image may provide a file /bin/walt-preinit
    # to load them.
    # note: "busybox modprobe" may cause dmesg warnings "Invalid ELF header magic"
    # when dealing with compressed kernel modules, so we prefer the modprobe command
    # provided by the OS if any.
    modules="crc32c overlay overlayfs ext4 nfs nfsv3 nbd zswap"
    more_modules=$(autodetect_block_modules)
    run_busybox_or_not --prefer-system \
        modprobe -a $modules $more_modules 2>/dev/null || true
    # loading a bus module may uncover another module needed, so re-run autodetection
    more_modules=$(autodetect_block_modules)
    run_busybox_or_not --prefer-system \
        modprobe -a $more_modules 2>/dev/null || true
}

preinit() {
    if [ -x "/bin/walt-preinit" ]
    then
        boot_step_label_cr          "Calling /bin/walt-preinit..."
        /bin/walt-preinit
    fi
}

prepare_rootfs()
{
    busybox mkdir -p $ROOTFS
    # $ROOTFS must be a mountpoint for pivot_root() to work later
    walt_mount -t tmpfs tmpfs $ROOTFS
    cd $ROOTFS
    busybox mkdir -p tmp bin mnt/nfsroot
    copy_exec_to_rootfs busybox
    if busybox which nbd-client >/dev/null
    then
        copy_exec_to_rootfs nbd-client
    fi
    for image_script in /bin/walt-* /bin/_walt_internal_/*
    do
        cp $image_script bin/
    done
    for c in $ROOTFS_BUSYBOX_APPLETS
    do
        if [ ! -e bin/$c ]
        then
            if busybox_has_applet $c
            then
                ln -s busybox bin/$c
            else
                copy_exec_to_rootfs $c
            fi
        fi
    done
    for fs_dir in proc sys dev run
    do
        ln -s ../mnt/nfsroot/$fs_dir $fs_dir
    done
    cd - >/dev/null
}

switch_to_rootfs() {
    cd $ROOTFS
    walt_switch_root_fs mnt/nfsroot \
        bin/walt-init-rootfs "$@"
}

# let's go
export PATH="$PATH:/bin/_walt_internal_"
export walt_init_done=0
. walt-script-common
walt-log-echo "walt-init" "Starting up."
boot_step_label_cr          "Initializing..."
do_mounts
load_modules
preinit
boot_step_label_cr          "Switching to rootfs..."
prepare_rootfs
switch_to_rootfs "$@"
# the process continues in bin/_walt_internal_/walt-init-rootfs
