#!/bin/sh
. walt-script-common
MSG_NO_BLINK_EXEC='/bin/blink unavailable or not executable on image'
MSG_BLINK_FAILED='/bin/blink returned a non-zero error code'

# save stdout as fd 8
# (because of the construct 'status=$(run_permanent_connection)' below)
exec 8>&1

wait_for_ssh() {
    while [ 1 ]
    do
        # if port 22 is opened, send empty line to let sshd
        # close the connection and let this nc command stop.
        if nostdout nostderr walt-timeout 5 busybox nc 127.0.0.1 22 << EOF

EOF
        then
            break  # OK, port 22 is ready to accept connections
        fi
        busybox sleep 1
    done
}

call_image_bootup_script() {
    if [ -f "/mnt/finalfs/bin/on-bootup" ]
    then
        if [ -x "/mnt/finalfs/bin/on-bootup" ]
        then
            do_on_finalfs /bin/on-bootup
        else
            echo "WARNING: cannot run /bin/on-bootup (execute permission missing)." >&2
        fi
    fi
}

remove_nologin() {
    busybox rm -f /mnt/finalfs/run/nologin
}

handle_blink() {
    # start /bin/blink [0|1] when we receive BLINK [0|1]
    shift  # ignore 1st arg "BLINK"
    if [ -x "/mnt/finalfs/bin/blink" ]; then
        if do_on_finalfs /bin/blink "$@" >&8; then
            # all is fine
            echo OK
        else
            # /bin/blink apparently failed
            echo KO $MSG_BLINK_FAILED
        fi
    else
        # no /bin/blink on this image
        echo KO $MSG_NO_BLINK_EXEC
    fi
}

handle_reboot() {
    # reboot the node when we receive REBOOT
    custom_script=$(get_custom_walt_reboot_script)
    if [ ! -z "$custom_script" ]
    then
        # try to run it
        if [ -x "/mnt/finalfs$custom_script" ]; then
            echo OK
            trigger_walt_reboot walt-custom-reboot $custom_script >&8
        else
            echo KO $custom_script is not executable on image
        fi
    else
        echo OK
        trigger_walt_reboot reboot >&8
    fi
}

get_custom_walt_reboot_script() {
    # custom rebooting is disabled for virtual nodes
    # "walt_vnode_mode" was passed as an env variable
    if [ "$walt_vnode_mode" -eq 1 ]
    then
        return
    fi
    if [ "${walt_boot_mode}" = "network-volatile" -o \
         "${walt_boot_mode}" = "network-persistent" ]
    then
        # /bin/walt-network-reboot (new image)
        if [ -e "/mnt/finalfs/bin/walt-network-reboot" ]; then
            echo "/bin/walt-network-reboot"
            return
        fi
        # legacy /bin/walt-reboot (old image)
        if [ -e "/mnt/finalfs/bin/walt-reboot" ]; then
            echo "/bin/walt-reboot"
            return
        fi
    else    # hybrid boot
        # /bin/walt-hybrid-reboot (new image)
        if [ -e "/mnt/finalfs/bin/walt-hybrid-reboot" ]; then
            echo "/bin/walt-hybrid-reboot"
            return
        fi
        # note: hybrid boot is unknown for old images
    fi
}

run_permanent_connection() {
    nc_fifo="/tmp/net-service-$$.fifo"
    [ -e $nc_fifo ] || mkfifo $nc_fifo
    {
        echo REQ_NODE_NET_SERVICE
        # It is important to keep nc stdin open until we detect a
        # disconnection, otherwise nc stops immediately.
        while true
        do
            if msg=$(wait_for_input_line_shortly 20 < $nc_fifo)
            then
                case "$msg" in
                    "STOP")
                        break
                        ;;
                    "BLINK"*)
                        handle_blink $msg
                        ;;
                    "REBOOT")
                        handle_reboot
                        ;;
                    *)
                        echo Unexpected "$msg" >&2
                        break
                        ;;
                esac
            else
                # Some versions of busybox nc fail to stop when the
                # remote end is closed. We send EOL chars periodically
                # (i.e. if no other message to transmit for 20s)
                # to detect this.
                echo
            fi
        done
    } | {
        busybox nc $walt_server_ip $walt_server_notify_bootup_port || true
    } | {
        connected=0
        # read OK from server within 3 seconds
        if msg_ok=$(wait_for_input_line_shortly 3)
        then
            if [ "$msg_ok" = "OK" ]
            then
                connected=1
                # Correct response obtained from server.
                # We can now listen indefinitely on connection,
                # and forward server requests (REBOOT, BLINK)
                # on the fifo.
                { cat; echo STOP; } > $nc_fifo
                # cat will stop when its input is closed,
                # i.e., when 'busybox nc' stops.
            fi
        fi
        # let the caller know what happened
        if [ $connected -eq 1 ]
        then
            # disconnection
            echo DISCONNECTED
        else
            # connection failure, stop the loop above
            echo STOP > $nc_fifo
            echo CONNECT_FAILED
        fi
    }
}

echo "[walt:bg] walt-net-service started."

# We consider the node is ready when its
# sshd service is ready to accept connections.
wait_for_ssh

# call script /bin/on-bootup if image provides it
call_image_bootup_script

# remove /run/nologin if present
# (if present a warning message may be printed when connecting
# very early and the OS considers bootup procedure is not complete)
remove_nologin

# save uptime to know when the OS got ready
[ ! -e /run/uptime-ready ] && cp /proc/uptime /run/uptime-ready

# we maintain a permanent connection to walt server.
# opening it will set our status to "booted".
# if this connection is closed on our side, the server
# can detect we are down. if this connection is closed
# on server side, we know that the server is down and
# images are probably umounted, so we reboot.
retries=2
while true
do
    status=$(run_permanent_connection)
    # in rare cases a TCP connection may fail, so we must try
    # a few times.
    if [ "$status" = "CONNECT_FAILED" -a $retries -gt 0 ]
    then
        retries=$((retries - 1))
        echo "[walt:bg] walt-net-service: reconnecting attempt after 5 seconds"
        busybox sleep 5
        continue
    else
        echo "[walt:bg] walt-net-service:" \
             "failed or lost connection to walt server!" >&2
        busybox sleep 3
        trigger_walt_reboot reboot
    fi
done
