#!/bin/busybox sh

ROOTFS='/mnt/memfs'
ROOTFS_EXECUTABLES="
    basename cat chroot cp date grep ln ls mkdir mkfifo mktemp
    mount mv nc reboot rm sed sh sleep timeout umount uname
"

. bin/_walt_internal_/walt-boot-modes  # needed for need_rw_networkfs()

_fs_is_mounted() {
    walt_mount | nostdout busybox grep " /$1 "
}

do_mounts()
{
    initial_mounts=""
    real_mounts=""
    # mount /proc, /sys, /run and /dev if missing, record what were
    # the initial mounts and what we have after that.
    # 1. /proc
    # We mount /proc first because _fs_is_mounted() needs it to work.
    if [ -e "/proc/self" ]
    then
        initial_mounts="$initial_mounts proc"
    else
        walt_mount -t proc proc /proc
        real_mounts="$real_mounts proc"
    fi
    # 2. /sys
    if _fs_is_mounted sys
    then
        initial_mounts="$initial_mounts sys"
    else
        walt_mount -t sysfs sysfs /sys
        real_mounts="$real_mounts sys"
    fi
    # 3. /run
    # We will only need /run later, so don't mount it yet
    # if it was not already mounted by an initramfs.
    if _fs_is_mounted run
    then
        initial_mounts="$initial_mounts run"
    fi
    # 4. /dev
    # Some minimal operating systems may manage device files
    # statically in /dev, without using a filesystem.
    if _fs_is_mounted dev
    then
        initial_mounts="$initial_mounts dev"
    elif [ ! -e "/dev/null" ]
    then
        walt_mount -t devtmpfs udev /dev
        real_mounts="$real_mounts dev"
    fi
    # add initial mounts to the list of real mounts
    # and export those variables for later use.
    export initial_mounts
    export real_mounts="${initial_mounts} ${real_mounts}"
}

preinit() {
    if [ -x "/bin/walt-preinit" ]
    then
        boot_step_label_cr          "Calling /bin/walt-preinit..."
        /bin/walt-preinit
    fi
    # call walt_preinit() optional function too,
    # if defined in walt-init-overrides.
    walt_preinit
}

prepare_memfs()
{
    walt_mount -t tmpfs tmpfs /mnt
    busybox mkdir -p $ROOTFS
    # create another mount for memfs because we will have to
    # move it later.
    walt_mount -t tmpfs tmpfs $ROOTFS
    cd $ROOTFS
    busybox mkdir -p tmp bin mnt/networkfs
    copy_exec_to_memfs busybox
    if nostdout busybox which nbd-client
    then
        copy_exec_to_memfs nbd-client
    fi
    for image_script in /bin/walt-* /bin/_walt_internal_/*
    do
        cp $image_script bin/
    done
    for c in $ROOTFS_EXECUTABLES
    do
        if [ ! -e bin/$c ]
        then
            if busybox_has_applet $c
            then
                ln -s busybox bin/$c
            else
                copy_exec_to_memfs $c
            fi
        fi
    done
    for fs in $real_mounts
    do
        ln -s mnt/networkfs/$fs .
    done
    dump_walt_env > bin/walt-env
    walt_populate_memfs_custom
}

remount_networkfs_if_needed()
{
    if need_rw_networkfs
    then
        boot_step_label_cr "Ensuring the remote filesystem" \
                           "is read-write..."
        walt_mount -o remount,rw /
    fi
}

mount_persistent() {
    if [ -z "${walt_persist_path}" ]
    then
        echo "/persist was not mounted (cf. walt node config)"
        return
    fi
    mkdir -p $ROOTFS/mnt/persist
    walt_mount_persistent "$walt_persist_path" $ROOTFS/mnt/persist
    # check if walt-init logs are enabled
    walt_init_log_dir="$ROOTFS/mnt/persist/logs/walt-init"
    if [ -d "$walt_init_log_dir" ]
    then
        # avoid NFS buffers by remounting with 'sync' option.
        # note: "mount -o remount,sync" fails on some systems,
        # so we umount + mount again.
        walt_umount $ROOTFS/mnt/persist
        walt_mount_persistent --sync "$walt_persist_path" $ROOTFS/mnt/persist
    fi
}

switch_to_memfs() {
    cd $ROOTFS
    walt_switch_root_fs mnt/networkfs \
        bin/walt-init-memfs "$@"
}

# Check we are PID 1.
if [ "$$" -ne 1 ]
then
    echo "This is the init script of walt nodes." >&2
    echo "It is only useful when the node is booting. Exiting." >&2
    exit 1
fi
# let's go
export PATH="$PATH:/bin/_walt_internal_"
export walt_init_done=0
# preparation work
. walt-init-common
# init env variables specific to the image or to the node
export walt_env="$(
    cat /bin/_walt_internal_/walt-env-image
    /bin/_walt_internal_/walt-fetch-node-config
)"
eval "$walt_env"
# redefine console
cd /; walt_set_console
# run image's preinit code if any
preinit
# real start
walt-log-echo "walt-init" "Starting up."
boot_step_label_cr          "Initializing..."
do_mounts
walt_set_console  # in case do_mounts() just mounted /dev
walt_load_kernel_modules
prepare_memfs
boot_step_label_cr          "Mounting /persist..."
mount_persistent
remount_networkfs_if_needed
boot_step_label_cr          "Updating network interface altname(s)..."
walt_set_network_names
boot_step_label_cr          "Switching to memfs..."
switch_to_memfs "$@"        # see bin/_walt_internal_/walt-init-memfs
