#!/bin/busybox sh

# preparation work
. walt-script-common
. walt-init-disks
. walt-boot-modes
. walt-clock-sync
. walt-init-nbd

# helper functions
enable_zswap() {
    # enable zswap if the kernel supports it, for more optimized RAM usage
    # (or limited NBD swap usage if NBD mounting succeeds)
    [ -e /sys/module/zswap/parameters/enabled ] && \
        echo 1 > /sys/module/zswap/parameters/enabled || true
}

# setting clock
if [ $walt_vnode_mode -eq 1 ]
then
    boot_step_label_cr "Setting clock... skipped (virtual node)"
else
    boot_step_label_cr "Setting clock..."
    sync_clock
fi
# mounting local swap partitions
if [ "$(possibly_vpn_node)" = "1" ]
then
    boot_step_label_cr \
        "Activating local swap... disabled (VPN security measure)"
    has_local_swap=0
else
    boot_step_label_cr \
        "Activating local swap..."
    if activate_local_swap
    then
        has_local_swap=1
    else
        has_local_swap=0
    fi
fi
# boot mode detection
boot_step_label_cr "Verifying boot-mode..."
verify_boot_mode
. /bin/walt-env  # reload in case walt_boot_mode variable was updated
# enable zswap
enable_zswap
# mount remote NBD swap
if [ "$has_local_swap" -eq 0 ]
then
    boot_step_label_cr "Mounting remote swap space on server..."
    mount_nbd_swap
else
    boot_step_label_cr "Mounting remote swap space on server... skipped"
    echo "Note: Preferring local swap."
fi
# mount the final root (at /mnt/finalfs for now)
mount_finalfs
# mount secondary filesystems
mount_secondaryfs
# the process now returns to bin/_walt_internal_/walt-init-rootfs
allow_script_exit
