#!/bin/sh

set -e
. walt-script-base

#if nostdout busybox which walt-clock-sync-native
#then
#    walt-clock-sync-native "$walt_server_ip" "$walt_server_syncd_port"
#    allow_script_exit
#    exit
#fi

input_manager() {
    # send busybox adjtimex data on the connection and quit
    # when output_manager() tells us to.
    while read verb args < /tmp/clock_sync.fifo
    do
        case "$verb" in
            "RUN_ADJTIME")
                busybox adjtimex
                echo
                ;;
            "QUIT")
                break
                ;;
        esac
    done
}

set_date_opt1() {
    # hopefully '@' epoch format is recognised
    busybox date -s @$1
}

set_date_opt2() {
    # fallback method if '@' epoch format is not recognised
    busybox date -s \
        "$(busybox date -D "%%s" -d $1 "+%%Y-%%m-%%d %%H:%%M:%%S")"
}

detect_set_date_function() {
    ts=$(busybox date +%%s)
    if nostdout nostderr set_date_opt1 $ts
    then
        set_date=set_date_opt1
    else
        set_date=set_date_opt2
    fi
}

output_manager() {
    retcode=0
    while read verb arg
    do
        case "$verb" in
            "SYNC")
                $set_date $arg
                ;;
            "ADJ_OFFSET")
                busybox adjtimex -o "$offset"
                ;;
            "ADJ_FREQ")
                busybox adjtimex -o "$freq"
                ;;
            "RUN_ADJTIME")
                echo "RUN_ADJTIME" > /tmp/clock_sync.fifo
                ;;
            "QUIT")
                echo "QUIT" > /tmp/clock_sync.fifo
                break
                ;;
        esac
    done
}

bg_process() {
    [ -e /tmp/clock_sync.fifo ] || busybox mkfifo /tmp/clock_sync.fifo
    input_manager | \
        busybox nc %(server_ip)s %(walt_server_syncd_port)s | \
    output_manager
    busybox rm -f /tmp/clock_sync.fifo
}

main() {
    detect_set_date_function
    bg_process &
}

main
