# auto-generated by dev/version/versions-updater.py

API_VERSIONING = dict(
    NODE = (1, '4e98f15d387a6638732d472758b63b30384e60dd21027e38952d54ba'),
    CLIENT = (1, '739de6909842303b769879a9b7e5f784bb8e93c2b51484ae9b43b0b8'),
    SERVER = (1, 'ae35a894d2cf7fda597c4f8d8152f682b2cfd6a2439e16cdfd221f3f')
)

UPLOAD = 4
