# auto-generated by dev/version/versions-updater.py

API_VERSIONING = dict(
    NODE = (1, '4e98f15d387a6638732d472758b63b30384e60dd21027e38952d54ba'),
    CLIENT = (1, '4b791069af76be4408ba2d5014b900c4d3faecde3d410d0b02c88ca0'),
    SERVER = (1, 'b8b07dc30b3b5d3c0d61e981fd8ee5e9ae62fb73f48a863c9ceabf9e')
)

UPLOAD = 1
